/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppShell: typeof import('./../components/AppShell.vue')['default']
    AppState: typeof import('./../components/AppState.vue')['default']
    AppTabbar: typeof import('./../components/AppTabbar.vue')['default']
    PpmxActionCard: typeof import('./../components/PpmxActionCard.vue')['default']
    PpmxBaseModal: typeof import('./../components/PpmxBaseModal.vue')['default']
    PpmxButton: typeof import('./../components/PpmxButton.vue')['default']
    PpmxDialog: typeof import('./../components/PpmxDialog.vue')['default']
    PpmxField: typeof import('./../components/PpmxField.vue')['default']
    PpmxGuestPanel: typeof import('./../components/PpmxGuestPanel.vue')['default']
    PpmxHomeShell: typeof import('./../components/PpmxHomeShell.vue')['default']
    PpmxIconBadge: typeof import('./../components/PpmxIconBadge.vue')['default']
    PpmxMoneyText: typeof import('./../components/PpmxMoneyText.vue')['default']
    PpmxPaymentSuccessNotice: typeof import('./../components/PpmxPaymentSuccessNotice.vue')['default']
    PpmxPromoCodeModal: typeof import('./../components/PpmxPromoCodeModal.vue')['default']
    PpmxRechargeModal: typeof import('./../components/PpmxRechargeModal.vue')['default']
    PpmxRechargePaymentModal: typeof import('./../components/PpmxRechargePaymentModal.vue')['default']
    PpmxSegmentedOptions: typeof import('./../components/PpmxSegmentedOptions.vue')['default']
    PpmxSelectInput: typeof import('./../components/PpmxSelectInput.vue')['default']
    PpmxSkeleton: typeof import('./../components/PpmxSkeleton.vue')['default']
    PpmxSocialModal: typeof import('./../components/PpmxSocialModal.vue')['default']
    PpmxSubpageLayout: typeof import('./../components/PpmxSubpageLayout.vue')['default']
    PpmxSupportModal: typeof import('./../components/PpmxSupportModal.vue')['default']
    PpmxThemeToggle: typeof import('./../components/PpmxThemeToggle.vue')['default']
    PpmxUnlockModal: typeof import('./../components/PpmxUnlockModal.vue')['default']
    PpmxWithdrawModal: typeof import('./../components/PpmxWithdrawModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanButton: typeof import('vant/es')['Button']
    VanIcon: typeof import('vant/es')['Icon']
    VanPopup: typeof import('vant/es')['Popup']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
  }
}
