/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    'home': RouteRecordInfo<
      'home',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'bank': RouteRecordInfo<
      'bank',
      '/bank',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'casino': RouteRecordInfo<
      'casino',
      '/casino',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'crypto-pay': RouteRecordInfo<
      'crypto-pay',
      '/crypto-pay',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'download': RouteRecordInfo<
      'download',
      '/download',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'gsc-sport-test': RouteRecordInfo<
      'gsc-sport-test',
      '/gsc-sport-test',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'guide': RouteRecordInfo<
      'guide',
      '/guide',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'play': RouteRecordInfo<
      'play',
      '/play',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'profile': RouteRecordInfo<
      'profile',
      '/profile',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'promo': RouteRecordInfo<
      'promo',
      '/promo',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'promo-detail': RouteRecordInfo<
      'promo-detail',
      '/promo/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    'recharge': RouteRecordInfo<
      'recharge',
      '/recharge',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'records': RouteRecordInfo<
      'records',
      '/records',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'responsible': RouteRecordInfo<
      'responsible',
      '/responsible',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'sec-email': RouteRecordInfo<
      'sec-email',
      '/sec-email',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'sec-password': RouteRecordInfo<
      'sec-password',
      '/sec-password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'sec-phone': RouteRecordInfo<
      'sec-phone',
      '/sec-phone',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'security': RouteRecordInfo<
      'security',
      '/security',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'team': RouteRecordInfo<
      'team',
      '/team',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'team-v2': RouteRecordInfo<
      'team-v2',
      '/team-v2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'user-profile': RouteRecordInfo<
      'user-profile',
      '/user-profile',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'vip': RouteRecordInfo<
      'vip',
      '/vip',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'wheel': RouteRecordInfo<
      'wheel',
      '/wheel',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/(home)/index.vue': {
      routes:
        | 'home'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/bank/index.vue': {
      routes:
        | 'bank'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/casino/index.vue': {
      routes:
        | 'casino'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/crypto-pay/index.vue': {
      routes:
        | 'crypto-pay'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/download/index.vue': {
      routes:
        | 'download'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/gsc-sport-test/index.vue': {
      routes:
        | 'gsc-sport-test'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/guide/index.vue': {
      routes:
        | 'guide'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/play/index.vue': {
      routes:
        | 'play'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/profile/index.vue': {
      routes:
        | 'profile'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/promo/index.vue': {
      routes:
        | 'promo'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/promo/[id].vue': {
      routes:
        | 'promo-detail'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/recharge/index.vue': {
      routes:
        | 'recharge'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/records/index.vue': {
      routes:
        | 'records'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/responsible/index.vue': {
      routes:
        | 'responsible'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/sec-email/index.vue': {
      routes:
        | 'sec-email'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/sec-password/index.vue': {
      routes:
        | 'sec-password'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/sec-phone/index.vue': {
      routes:
        | 'sec-phone'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/security/index.vue': {
      routes:
        | 'security'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/team/index.vue': {
      routes:
        | 'team'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/team-v2/index.vue': {
      routes:
        | 'team-v2'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/user-profile/index.vue': {
      routes:
        | 'user-profile'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/vip/index.vue': {
      routes:
        | 'vip'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/wheel/index.vue': {
      routes:
        | 'wheel'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
