import { describe, expect, it } from 'vitest'

const { existsSync, readFileSync } = await import('node:' + 'fs')
const { readdir } = await import('node:' + 'fs/promises')
const readSource = (path: string) =>
  readFileSync(new URL(`../../${path}`, import.meta.url), 'utf8')
const existsSource = (path: string) => existsSync(new URL(`../../${path}`, import.meta.url))

describe('PP.MX routed pages structure', () => {
  it('keeps routed page SFCs inside dedicated page folders', async () => {
    const entries = await readdir(new URL('../../src/pages/', import.meta.url), {
      withFileTypes: true,
    }) as Array<{ isFile: () => boolean; name: string }>
    const topLevelVuePages = entries
      .filter((entry) => entry.isFile() && entry.name.endsWith('.vue'))
      .map((entry) => entry.name)

    expect(topLevelVuePages).toEqual([])
    expect(existsSource('src/pages/(home)/index.vue')).toBe(true)
    expect(existsSource('src/pages/wheel/index.vue')).toBe(true)
    expect(existsSource('src/pages/team/index.vue')).toBe(true)
    expect(existsSource('src/pages/team-v2/index.vue')).toBe(true)
    expect(existsSource('src/pages/promo/index.vue')).toBe(true)
    expect(existsSource('src/pages/promo/[id].vue')).toBe(true)
    expect(existsSource('src/pages/profile/index.vue')).toBe(true)
    expect(existsSource('src/pages/records/index.vue')).toBe(true)
    expect(existsSource('src/pages/security/index.vue')).toBe(true)
    expect(existsSource('src/pages/sec-password/index.vue')).toBe(true)
    expect(existsSource('src/pages/sec-email/index.vue')).toBe(true)
    expect(existsSource('src/pages/sec-phone/index.vue')).toBe(true)
    expect(existsSource('src/pages/casino/index.vue')).toBe(true)
    expect(existsSource('src/pages/play/index.vue')).toBe(true)
    expect(existsSource('src/pages/user-profile/index.vue')).toBe(true)
    expect(existsSource('src/pages/recharge/index.vue')).toBe(true)
    expect(existsSource('src/pages/bank/index.vue')).toBe(true)
    expect(existsSource('src/pages/vip/index.vue')).toBe(true)
    expect(existsSource('src/pages/responsible/index.vue')).toBe(true)
    expect(existsSource('src/pages/guide/index.vue')).toBe(true)
  })

  it('removes obsolete default H5 login and mine pages from active routing', () => {
    const activeShellSource = [
      'src/components/AppShell.vue',
      'src/components/AppTabbar.vue',
      'src/router/index.ts',
      'src/utils/http.ts',
    ].map(readSource).join('\n')

    expect(existsSource('src/pages/login/index.vue')).toBe(false)
    expect(existsSource('src/pages/mine/index.vue')).toBe(false)
    expect(activeShellSource).not.toContain('/login')
    expect(activeShellSource).not.toContain('/mine')
    expect(activeShellSource).toContain('/profile')
  })

  it('adds routed wheel, team, promo, and profile pages under the PP.MX shell', () => {
    for (const page of ['wheel', 'team', 'promo', 'profile', 'records', 'security', 'sec-password', 'sec-email', 'sec-phone', 'casino', 'user-profile', 'recharge', 'bank', 'vip', 'responsible', 'guide']) {
      const path = `src/pages/${page}/index.vue`

      expect(existsSource(path)).toBe(true)
      expect(readSource(path)).toContain("shell: 'ppmx'")
    }
  })

  it('uses a shared PP.MX page chrome instead of duplicating header and auth shell logic', () => {
    const chromePath = 'src/pages/ppmx-home/components/PpmxPageChrome.vue'
    const chromeSource = readSource(chromePath)

    expect(existsSource(chromePath)).toBe(true)
    expect(readSource('src/pages/ppmx-home/PpmxHome.vue')).toContain('PpmxPageChrome')
    expect(chromeSource).toContain('requireRegisterAuth')
    expect(chromeSource).toContain("openAuth('register')")

    for (const page of ['wheel', 'team', 'promo', 'profile', 'records', 'casino', 'user-profile', 'recharge', 'bank', 'vip', 'responsible']) {
      expect(readSource(`src/pages/${page}/index.vue`)).toContain('PpmxPageChrome')
    }
    expect(readSource('src/pages/security/index.vue')).toContain('PpmxSubpageLayout')
    expect(readSource('src/pages/sec-password/index.vue')).toContain('PpmxSubpageLayout')
    expect(readSource('src/pages/sec-email/index.vue')).toContain('PpmxSubpageLayout')
    expect(readSource('src/pages/sec-phone/index.vue')).toContain('PpmxSubpageLayout')
    expect(readSource('src/pages/guide/index.vue')).toContain('PpmxSubpageLayout')
    expect(readSource('src/components/PpmxSubpageLayout.vue')).toContain('PpmxPageChrome')
  })

  it('extracts common PP.MX primitives for repeated page structure', () => {
    const buttonSource = readSource('src/components/PpmxButton.vue')
    const baseModalSource = readSource('src/components/PpmxBaseModal.vue')
    const withdrawModalSource = readSource('src/components/PpmxWithdrawModal.vue')
    const actionCardSource = readSource('src/components/PpmxActionCard.vue')
    const segmentedSource = readSource('src/components/PpmxSegmentedOptions.vue')
    const fieldSource = readSource('src/components/PpmxField.vue')
    const moneySource = readSource('src/components/PpmxMoneyText.vue')
    const requestSource = readSource('src/composables/usePpmxPageRequest.ts')

    expect(buttonSource).toContain("defineOptions({ name: 'PpmxButton' })")
    expect(baseModalSource).toContain("defineOptions({ name: 'PpmxBaseModal' })")
    expect(withdrawModalSource).toContain("class=\"ppmx-withdraw-modal\"")
    expect(actionCardSource).toContain("class=\"ppmx-action-card\"")
    expect(actionCardSource).toContain('PpmxIconBadge')
    expect(segmentedSource).toContain('ppmx-segmented-options')
    expect(fieldSource).toContain('fieldClass')
    expect(moneySource).toContain('formatMoney')
    expect(requestSource).toContain('usePageState')
    expect(requestSource).toContain('state.startLoading')
  })

  it('wires the PP.MX dark and light theme toggle into shared chrome and account page', () => {
    const componentSource = readSource('src/components/PpmxThemeToggle.vue')
    const composableSource = readSource('src/composables/usePpmxTheme.ts')
    const storeSource = readSource('src/stores/app.ts')
    const chromeSource = readSource('src/pages/ppmx-home/components/PpmxPageChrome.vue')
    const profileSource = readSource('src/pages/profile/index.vue')
    const indexSource = readSource('index.html')

    expect(componentSource).toContain("defineOptions({ name: 'PpmxThemeToggle' })")
    expect(componentSource).toContain('theme-btn')
    expect(componentSource).toContain('theme-ico')
    expect(componentSource).toContain('@click="toggleTheme"')
    expect(composableSource).toContain('usePpmxTheme')
    expect(composableSource).toContain('themeIconClass')
    expect(storeSource).toContain("const THEME_STORAGE_KEY = 'ppmx_theme'")
    expect(storeSource).toContain("const theme = ref<ThemeMode>(readPersistedTheme())")
    expect(storeSource).toContain('function toggleTheme()')
    expect(storeSource).toContain('function initTheme()')
    expect(indexSource).toContain("localStorage.getItem('ppmx_theme')")
    expect(indexSource).toContain("document.documentElement.dataset.theme = theme")
    expect(chromeSource).toContain('PpmxThemeToggle')
    expect(chromeSource).toContain('ppmx-theme-toggle--drawer')
    expect(profileSource).toContain('PpmxThemeToggle')
    expect(profileSource).toContain('PpmxGuestPanel')
    expect(profileSource).toContain('ppmx-account-theme')
    expect(profileSource).toContain('show-toggle-label')
    expect(profileSource).toContain('id="accGuest"')
    expect(profileSource).toContain('@secondary="openAuth(\'login\')"')
    expect(profileSource).toContain('@primary="openAuth(\'register\')"')
    expect(profileSource).not.toContain('class="ppmx-account-guest reveal"')
    expect(profileSource).not.toContain('themeSoon')
    expect(profileSource).not.toContain('Tema próximamente')
  })

  it('adds a dedicated mobile bottom navigation to the PP.MX shell', () => {
    const shellSource = readSource('src/components/PpmxHomeShell.vue')
    const stylesSource = readSource('src/assets/styles/pp-mx-home.css')

    expect(shellSource).toContain('ppmx-mobile-tabbar')
    expect(shellSource).toContain("path: '/'")
    expect(shellSource).toContain("path: '/wheel'")
    expect(shellSource).toContain("path: '/team'")
    expect(shellSource).toContain("path: '/promo'")
    expect(shellSource).toContain("path: '/profile'")
    expect(shellSource).toContain("zh: '首页'")
    expect(shellSource).toContain('pickText(item.label)')
    expect(stylesSource).toContain('.ppmx-mobile-tabbar')
    expect(stylesSource).toContain('rgba(28, 21, 40, 0.98)')
    expect(stylesSource).toContain('rgba(14, 13, 18, 0.98)')
    expect(stylesSource).toContain('left: 0')
    expect(stylesSource).toContain('right: 0')
    expect(shellSource).toContain('lg:hidden fixed bottom-0 inset-x-0 z-40 glass-strong border-t border-white/8 grid grid-cols-5 text-[11px]')
    expect(shellSource).toContain('data-page')
    expect(shellSource).toContain('href="#"')
    expect(shellSource).toContain('text-zinc-500')
    expect(shellSource).toContain('text-oro-400')
  })

  it('connects the PP.MX daily check-in modal from the floating shortcut', () => {
    const source = readSource('src/pages/ppmx-home/PpmxHome.vue')
    const apiSource = readSource('src/api/user.ts')
    const stylesSource = readSource('src/assets/styles/pp-mx-home.css')

    expect(source).toContain('checkinModalOpen')
    expect(source).toContain('openCheckinModal')
    expect(source).toContain('closeCheckinModal')
    expect(source).toContain('claimCheckin')
    expect(source).toContain('loadCheckinData')
    expect(source).toContain('getCheckInStatus')
    expect(source).toContain('doCheckIn')
    expect(source).toContain('getCheckInRecords')
    expect(source).toContain('id="checkinModal"')
    expect(source).toContain('id="checkinGrid"')
    expect(source).toContain('id="checkinBtn"')
    expect(source).toContain('ppmx-checkin-modal')
    expect(apiSource).toContain('export interface CheckInStatusResp')
    expect(apiSource).toContain("get<CheckInStatusResp>('/v1/app/checkin/status')")
    expect(apiSource).toContain("post<CheckInResp>('/v1/app/checkin', {})")
    expect(apiSource).toContain('get<CheckInRecordItem[]>(`/v1/app/checkin/records?limit=${limit}`)')
    expect(apiSource).not.toContain("'/api/v1/app/checkin")
    expect(stylesSource).toContain('.ppmx-checkin-modal')
    expect(stylesSource).toContain('.ppmx-checkin-grid')
    expect(stylesSource).toContain('.ppmx-checkin-tile')
  })

  it('connects the PP.MX official social channels modal from the floating shortcut', () => {
    const source = readSource('src/pages/ppmx-home/PpmxHome.vue')
    const dataSource = readSource('src/pages/ppmx-home/data.ts')
    const stylesSource = readSource('src/assets/styles/pp-mx-home.css')

    expect(source).toContain('socialModalOpen')
    expect(source).toContain('openSocialModal')
    expect(source).toContain('closeSocialModal')
    expect(source).toContain('openSocialChannel')
    expect(source).toContain('ppmxSocialText')
    expect(source).toContain('id="socialModal"')
    expect(source).toContain('ppmx-social-modal')
    expect(source).toContain('ppmx-social-grid')
    expect(dataSource).toContain('export const ppmxSocialText')
    expect(dataSource).toContain('https://www.instagram.com/ppus/')
    expect(dataSource).toContain('https://t.me/ppus')
    expect(stylesSource).toContain('.ppmx-social-modal')
    expect(stylesSource).toContain('.ppmx-social-grid')
    expect(stylesSource).toContain('.ppmx-social-card')
  })

  it('connects the PP.MX app download page from floating and account entry points', () => {
    const source = readSource('src/pages/download/index.vue')
    const homeSource = readSource('src/pages/ppmx-home/PpmxHome.vue')
    const chromeSource = readSource('src/pages/ppmx-home/components/PpmxPageChrome.vue')
    const profileSource = readSource('src/pages/profile/index.vue')
    const dataSource = readSource('src/pages/ppmx-home/pageData.ts')
    const stylesSource = readSource('src/assets/styles/pp-mx-home.css')

    expect(source).toContain("name: 'download'")
    expect(source).toContain('ppmx-download-page')
    expect(source).toContain('ppmxDownloadText')
    expect(source).toContain('ppmxDownloadFeatures')
    expect(source).toContain('ppmxDownloadSteps')
    expect(source).toContain('downloadApp')
    expect(source).toContain('downloadIosWebClipProfile')
    expect(source).toContain('ppmx-ios.mobileconfig')
    expect(source).toContain('App Store')
    expect(source).toContain('Android APK')
    expect(source).toContain('https://pub-93b0b439f98b49c4ba1db81844583907.r2.dev/PPMX.apk')
    expect(source).toContain('window.location.href = PPMX_ANDROID_APK_URL')
    expect(source).toContain("import QRCode from 'qrcode'")
    expect(source).toContain('QRCode.toDataURL(PPMX_ANDROID_APK_URL')
    expect(source).toContain('downloadQrDataUrl')
    expect(source).toContain(':src="downloadQrDataUrl"')
    expect(readSource('src/utils/iosWebClip.ts')).toContain('com.apple.webClip.managed')
    expect(readSource('src/utils/iosWebClip.ts')).toContain('window.location.origin')
    expect(readSource('src/utils/iosWebClip.ts')).toContain('import.meta.env.BASE_URL')
    expect(homeSource).toContain("target === 'download'")
    expect(homeSource).toContain("void router.push('/download')")
    expect(chromeSource).toContain("target === 'download'")
    expect(chromeSource).toContain("return '/download'")
    expect(profileSource).toContain("item.id === 'download'")
    expect(profileSource).toContain("void router.push('/download')")
    expect(dataSource).toContain('export const ppmxDownloadText')
    expect(dataSource).toContain('export const ppmxDownloadFeatures')
    expect(dataSource).toContain('export const ppmxDownloadSteps')
    expect(stylesSource).toContain('.ppmx-download-page')
    expect(stylesSource).toContain('.ppmx-download-hero')
    expect(stylesSource).toContain('.ppmx-download-steps')
  })

  it('connects the PP.MX activity guide page from the account entry point', () => {
    const source = readSource('src/pages/guide/index.vue')
    const profileSource = readSource('src/pages/profile/index.vue')
    const chromeSource = readSource('src/pages/ppmx-home/components/PpmxPageChrome.vue')
    const layoutSource = readSource('src/components/PpmxSubpageLayout.vue')
    const dataSource = readSource('src/pages/ppmx-home/pageData.ts')
    const stylesSource = readSource('src/assets/styles/pp-mx-home.css')
    const typesSource = readSource('src/pages/ppmx-home/types.ts')

    expect(source).toContain("name: 'guide'")
    expect(source).toContain('requiresAuth: true')
    expect(source).toContain('page-id="page-guide"')
    expect(source).toContain('PpmxSubpageLayout')
    expect(source).toContain('ppmxGuideText')
    expect(source).toContain('ppmxGuideCards')
    expect(source).toContain('ppmx-guide-card')
    expect(profileSource).toContain("item.id === 'guide'")
    expect(profileSource).toContain("router.push('/guide')")
    expect(chromeSource).toContain("target === 'guide'")
    expect(chromeSource).toContain("return '/guide'")
    expect(layoutSource).toContain('pageId?: string')
    expect(layoutSource).toContain(':id="props.pageId || undefined"')
    expect(dataSource).toContain('export const ppmxGuideText')
    expect(dataSource).toContain('export const ppmxGuideCards')
    expect(dataSource).toContain('fa-calendar-check')
    expect(dataSource).toContain("id: 'checkin'")
    expect(dataSource).toContain("id: 'wheel'")
    expect(dataSource).toContain("id: 'referral'")
    expect(dataSource).toContain("id: 'vip'")
    expect(dataSource).toContain("id: 'welcome'")
    expect(dataSource).toContain("id: 'download'")
    expect(dataSource).toContain('活动讲解')
    expect(dataSource).toContain('每周最高 $??? MXN')
    expect(dataSource).toContain('参与游戏获得免费旋转')
    expect(dataSource).toContain('每笔充值最高返佣 50%')
    expect(dataSource).toContain('周薪 + 升级奖励')
    expect(dataSource).toContain('100% 立即获得 $58 比索')
    expect(dataSource).toContain('登录即送 $8 MXN')
    expect(stylesSource).toContain('.ppmx-guide-page')
    expect(stylesSource).toContain('.ppmx-guide-card')
    expect(stylesSource).toContain('html[data-theme="light"] .ppmx-guide-card')
    expect(typesSource).toContain("| 'guide'")
    expect(typesSource).toContain('export interface PpmxGuideCard')
  })

  it('restores the lucky wheel page primitives from the PP.MX reference', () => {
    const source = readSource('src/pages/wheel/index.vue')
    const apiSource = readSource('src/api/user.ts')

    expect(source).toContain('ppmx-wheel-stage')
    expect(source).toContain('ppmx-wheel-hub')
    expect(source).toContain('ppmx-wheel-spin-button')
    expect(source).toContain('ppmx-wheel-rules')
    expect(source).toContain('ppmx-wheel-winfx')
    expect(source).toContain('requireRegisterAuth')
    expect(source).toContain('getLotteryChances')
    expect(source).toContain('drawLottery')
    expect(source).toContain('getPrizePoolBalance')
    expect(source).toContain("const PRIZE_COLORS = ['#c8102e', '#138a52']")
    expect(source).toContain("const PRIZE_GOLD_COLOR = '#f0bc3d'")
    expect(source).toContain('index === amounts.length - 1')
    expect(source).toContain('loadWheelData')
    expect(source).toContain('STATIC_WHEEL_AMOUNTS')
    expect(source).toContain('applyStaticWheelData')
    expect(source).toContain('if (!userStore.isLogin)')
    expect(source).toContain('showWheelJackpot')
    expect(source).toContain('<section v-if="showWheelJackpot" class="ppmx-wheel-jackpot">')
    expect(source).toContain('wheelPrizes')
    expect(source).toContain('jackpotDisplay')
    expect(source).toContain('AppState')
    expect(source).not.toContain('ppmx-wheel-records')
    expect(source).not.toContain('getPrizePoolOutRecords')
    expect(source).not.toContain('pickPrizeIndex')
    expect(source).not.toContain('Math.random() * totalWeight')
    expect(apiSource).toContain("get<LotteryChancesResp>('/v1/app/lottery/chances'")
    expect(apiSource).toContain("post<LotteryDrawResp>('/v1/app/lottery/draw'")
    expect(apiSource).toContain('get<PrizePoolBalanceResp>(`/v1/app/prizePool/balance?poolCode=${poolCode}`)')
    expect(apiSource).toContain('get<PrizePoolOutRecordResp>(`/v1/app/prizePool/outRecords?currentPage=${currentPage}&pageSize=${pageSize}`)')
  })

  it('uses the PP.MX team v2 implementation for the routed team page', () => {
    const source = readSource('src/pages/team/index.vue')
    const apiSource = readSource('src/api/user.ts')
    const esSource = readSource('src/locales/es-MX.ts')
    const enSource = readSource('src/locales/en-US.ts')
    const zhSource = readSource('src/locales/zh-CN.ts')

    expect(source).toContain("name: 'team'")
    expect(source).toContain('id="page-team"')
    expect(source).toContain('ppmx-team-v2-page')
    expect(source).toContain('teamV2Commission')
    expect(source).toContain('teamV2Kpis')
    expect(source).toContain('teamV2Invite')
    expect(source).toContain('teamV2Rules')
    expect(source).not.toContain('teamV2Rebate')
    expect(source).toContain('rechargeRebateRows')
    expect(source).toContain('ppmx.team.rechargeRebateTitle')
    expect(source).toContain('ppmx-team-rebate')
    expect(source).toContain('rechargeRebateFirst')
    expect(source).not.toContain('rechargeRebateThird')
    expect(source).not.toContain('rechargeRebateSecond')
    expect(source).not.toContain('inviteRechargeRebateRates')
    expect(source).toContain('PpmxGuestPanel')
    expect(source).toContain('@primary="requireRegisterAuth"')
    expect(source).toContain('inviteLink')
    expect(source).toContain('QRCode.toDataURL')
    expect(source).toContain('inviteQrDataUrl')
    expect(source).toContain('copyInvite')
    expect(source).toContain('ppmx-team-v2-qr')
    expect(source).toContain(':src="inviteQrDataUrl"')
    expect(source).toContain('claimTaskActivity')
    expect(source).toContain('rewardTaskActivity')
    expect(source).toContain('getTaskActivityList')
    expect(source).toContain('getTaskActivityRecords')
    expect(source).toContain('taskHistoryOpen')
    expect(source).toContain('openBank')
    expect(source).toContain('PpmxWithdrawModal')
    expect(source).toContain('PpmxSelectInput')
    expect(source).toContain('transferRebateToBalance')
    expect(source).toContain('createRebateWithdrawOrder')
    expect(source).toContain('getWithdrawAccounts')
    expect(source).toContain('id="teamV2TaskHistoryModal"')
    expect(source).toContain('id="teamV2CommissionWithdrawModal"')
    expect(source).toContain('id="teamV2TransferModal"')
    expect(source).toContain('@click="openCommissionWithdrawModal"')
    expect(source).toContain('submitCommissionWithdrawOrder')
    expect(source).toContain('MIN_COMMISSION_WITHDRAW_AMOUNT = 50')
    expect(source).toContain("router.push('/bank')")
    expect(apiSource).toContain("post<RebateWithdrawOrderResp>('/v1/app/tg/rebate/withdraw'")
    expect(source).toContain('requireRegisterAuth')
    expect(source).toContain('getCurrentTgInviteStats')
    expect(source).toContain('getCurrentTgInviteRuleConfig')
    expect(source).toContain("t('ppmx.team.ruleItem4')")
    expect(source).not.toContain("t('ppmx.team.ruleItem1')")
    expect(esSource).toContain('rechargeRebateTitle')
    expect(enSource).toContain('rechargeRebateTitle')
    expect(zhSource).toContain('rechargeRebateTitle')
    expect(zhSource).not.toContain('首次充值返 40%')
    expect(source).toContain('AppState')
    expect(source).toContain('teamError')
    expect(source).not.toContain('ppmx-team-auth')
    expect(source).not.toContain('ppmxTeamKpis')
    expect(source).not.toContain('ppmxCommissionSummary')
    expect(apiSource).toContain("get<TgInviteStats>('/v1/app/tg/inviteStats')")
    expect(apiSource).toContain("get<TgInviteRuleConfig>('/v1/app/tg/inviteRuleConfig')")
    expect(apiSource).toContain("post<TgRebateTransferResp>('/v1/app/tg/rebate/transfer'")
  })

  it('adds a standalone PP.MX team v2 page from the page-team reference', () => {
    const source = readSource('src/pages/team-v2/index.vue')
    const apiSource = readSource('src/api/user.ts')
    const stylesSource = readSource('src/assets/styles/pp-mx-home.css')

    expect(source).toContain("name: 'team-v2'")
    expect(source).toContain("titleKey: 'ppmx.team.title'")
    expect(source).toContain('id="page-team-v2"')
    expect(source).toContain('ppmx-team-v2-page')
    expect(source).toContain('teamV2TaskTiers')
    expect(source).toContain('teamV2Commission')
    expect(source).toContain('teamV2Kpis')
    expect(source).toContain('teamV2Invite')
    expect(source).toContain('teamV2Rules')
    expect(source).not.toContain('teamV2Rebate')
    expect(source).toContain('getCurrentTgInviteStats')
    expect(source).toContain('getCurrentTgInviteRuleConfig')
    expect(source).toContain('transferRebateToBalance')
    expect(source).toContain('QRCode.toDataURL')
    expect(source).toContain('PpmxGuestPanel')
    expect(source).toContain('AppState')
    expect(source).toContain('PpmxWithdrawModal')
    expect(source).toContain('PpmxPageChrome')
    expect(source).not.toContain('rechargeRebateRows')
    expect(source).not.toContain('inviteRechargeRebateRates')
    expect(source).toContain("router.push('/bank')")
    expect(apiSource).toContain("get<TgInviteStats>('/v1/app/tg/inviteStats')")
    expect(apiSource).toContain("post<TgRebateTransferResp>('/v1/app/tg/rebate/transfer'")
    expect(stylesSource).toContain('.ppmx-team-v2-page')
    expect(stylesSource).toContain('.ppmx-team-v2-task')
    expect(stylesSource).toContain('.ppmx-team-v2-commission')
    expect(stylesSource).toContain('.ppmx-team-v2-invite')
    expect(stylesSource).not.toContain('.ppmx-team-v2-rebate')
  })

  it('restores the promo page primitives from the PP.MX reference', () => {
    const source = readSource('src/pages/promo/index.vue')
    const detailSource = readSource('src/pages/promo/[id].vue')
    const detailComponentSource = readSource('src/pages/ppmx-home/components/PpmxPromoDetail.vue')
    const homeSource = readSource('src/pages/ppmx-home/PpmxHome.vue')
    const dataSource = readSource('src/pages/ppmx-home/pageData.ts')
    const chromeSource = readSource('src/pages/ppmx-home/components/PpmxPageChrome.vue')

    expect(source).toContain('id="page-promo"')
    expect(source).toContain('ppmx-promo-page')
    expect(source).toContain('id="promoList"')
    expect(source).toContain('promosGrid')
    expect(source).toContain('ppmx-promo-card')
    expect(source).toContain('`/promo/${promo.id}`')
    expect(source).toContain('highlightPromoText')
    expect(source).toContain('v-html="highlightPromoText(pickText(promo.title))"')
    expect(source).toContain('promo.backgroundImage')
    expect(source).toContain('promo.backgroundPosition')
    expect(source).not.toContain("query: { id: promo.id }")
    expect(source).not.toContain('id="promoDetail"')
    expect(detailSource).toContain('id="page-promo"')
    expect(detailSource).toContain('selectedPromo')
    expect(detailSource).toContain('PpmxPromoDetail')
    expect(detailSource).toContain('router.replace(\'/promo\')')
    expect(detailSource).toContain('requireRegisterAuth')
    expect(detailSource).toContain("selectedPromoId.value === 'registro'")
    expect(detailSource).toContain("void router.push('/profile')")
    expect(detailSource).not.toContain('promoCodeModalOpen')
    expect(detailSource).not.toContain('PpmxPromoCodeModal')
    expect(detailComponentSource).toContain('defineOptions({ name: \'PpmxPromoDetail\' })')
    expect(detailComponentSource).toContain('highlightPromoText')
    expect(detailComponentSource).toContain('id="promoDetail"')
    expect(detailComponentSource).toContain('v-html="highlightPromoText')
    expect(detailComponentSource).toContain('selectedPromo.backgroundImage')
    expect(detailComponentSource).toContain('selectedPromo.backgroundPosition')
    expect(homeSource).toContain('`/promo/${bannerId}`')
    expect(homeSource).not.toContain('query: { banner: bannerId }')
    expect(dataSource).toContain("id: 'registro'")
    expect(dataSource).toContain("id: 'checkin'")
    expect(dataSource).toContain("id: 'vip'")
    expect(dataSource).toContain("id: 'invita'")
    expect(dataSource).toContain("id: 'recarga'")
    expect(dataSource).toContain("id: 'download'")
    expect(dataSource).toContain("id: 'wheel'")
    expect(dataSource).toContain("title: { es: 'Regístrate y gana $58 MXN gratis'")
    expect(dataSource).toContain("title: { es: 'Check-in de nuevos: gana hasta $888 en 7 días'")
    expect(dataSource).toContain("title: { es: 'Sube de nivel VIP y reclama hasta $188,888'")
    expect(dataSource).toContain("title: { es: 'Hasta 50% de comisión'")
    expect(dataSource).toContain('Primera recarga: 40% de comisión')
    expect(dataSource).toContain('Tercera recarga o más: 50% de comisión')
    expect(dataSource).toContain('Comisión según el número de recarga del referido')
    expect(dataSource).toContain("title: { es: 'Nuevo usuario: recarga y recibe hasta 25% de regalo'")
    expect(dataSource).toContain("zh: '最高30%赠送'")
    expect(dataSource).not.toContain("title: { es: 'Recarga hoy y recibe +25% de bono'")
    expect(dataSource).toContain("title: { es: 'Descarga la app PP.MX y gana $8'")
    expect(dataSource).toContain("title: { es: 'Gira la ruleta y gana hasta $10,000'")
    expect(dataSource).toContain("backgroundImage: '/images/ppmx/promos/registro.jpg'")
    expect(dataSource).toContain("backgroundImage: '/images/ppmx/promos/checkin.jpg'")
    expect(dataSource).toContain("backgroundImage: '/images/ppmx/promos/vip.jpg'")
    expect(dataSource).toContain("backgroundImage: '/images/ppmx/promos/invita.jpg'")
    expect(dataSource).toContain("backgroundImage: '/images/ppmx/promos/recarga.jpg'")
    expect(dataSource).toContain("backgroundImage: '/images/ppmx/promos/download.jpg'")
    expect(dataSource).toContain("backgroundImage: '/images/ppmx/promos/wheel.jpg'")
    expect(dataSource).not.toContain("id: 'p-deposito'")
    for (const image of ['registro', 'checkin', 'vip', 'invita', 'recarga', 'download', 'wheel']) {
      expect(existsSource(`public/images/ppmx/promos/${image}.jpg`)).toBe(true)
    }
    expect(chromeSource).toContain("target === 'promo'")
    expect(chromeSource).toContain("return '/promo'")
  })

  it('restores the account page primitives from the PP.MX reference', () => {
    const source = readSource('src/pages/profile/index.vue')
    const apiSource = readSource('src/api/user.ts')
    const stylesSource = readSource('src/assets/styles/pp-mx-home.css')

    expect(source).toContain('PpmxGuestPanel')
    expect(source).toContain('id="accGuest"')
    expect(source).toContain('ppmx-account-view')
    expect(source).toContain('ppmx-account-balance')
    expect(source).toContain('bankPrompt')
    expect(source).toContain('ppmx-account-bank-prompt__icon')
    expect(source).toContain('ppmx-account-bank-prompt__content')
    expect(source).toContain('ppmx-account-bank-prompt__cta')
    expect(source).toContain('ppmx-account-hub')
    expect(source).toContain('PpmxActionCard')
    expect(source).toContain('PpmxMoneyText')
    expect(source).toContain('promoModalOpen')
    expect(source).toContain('openPromoModal')
    expect(source).toContain('submitPromoCode')
    expect(source).toContain('id="promoModal"')
    expect(source).toContain('id="promoInput"')
    expect(source).toContain('ppmx-promo-code-modal')
    expect(source).toContain('ppmx-account-hub-card--promo')
    expect(source).toContain('logoutAccount')
    expect(source).toContain('logoutDialogOpen')
    expect(source).toContain('openLogoutDialog')
    expect(source).toContain('ppmx-account-logout ppmx-glass reveal')
    expect(source).toContain('@click="openLogoutDialog"')
    expect(source).toContain('PpmxDialog')
    expect(source).toContain('@confirm="logoutAccount"')
    expect(source).toContain('withdrawModalOpen')
    expect(source).toContain('openWithdrawModal')
    expect(source).toContain('closeWithdrawModal')
    expect(source).toContain('submitWithdraw')
    expect(source).toContain('createWithdrawOrderV2')
    expect(source).toContain('getCurrentTgWithdrawFlowBatchSummary')
    expect(source).toContain('useSubmitLock')
    expect(source).toContain('countryCode: APP_COUNTRY_CODE')
    expect(source).toContain('fieldValues: buildWithdrawFieldValues()')
    expect(source).toContain('id="withdrawModal"')
    expect(source).toContain('id="wdAccount"')
    expect(source).toContain('PpmxWithdrawModal')
    expect(source).toContain('PpmxRechargeModal')
    expect(source).toContain('rechargeModalOpen')
    expect(source).toContain('wd-wager')
    expect(source).toContain('requireRegisterAuth')
    expect(source).not.toContain('requiresAuth: true')
    expect(source).not.toContain("router.push('/recharge')")
    expect(source).toContain("router.push('/bank')")
    expect(source).toContain("router.push('/records')")
    expect(source).toContain("router.push('/security')")
    expect(source).toContain("router.push('/user-profile')")
    expect(stylesSource).toContain('.ppmx-withdraw-modal')
    expect(stylesSource).toContain('.ppmx-account-bank-prompt__icon')
    expect(stylesSource).toContain('.ppmx-account-bank-prompt__cta')
    expect(stylesSource).toContain('.ppmx-account-hub-card--promo')
    expect(stylesSource).toContain('.ppmx-promo-code-input')
    expect(stylesSource).toContain('.wd-wager')
    expect(stylesSource).toContain('.wd-fees')
    expect(apiSource).toContain('export interface CreateWithdrawOrderReq')
    expect(apiSource).toContain('export interface TgWithdrawFlowBatchSummary')
    expect(apiSource).toContain("get<TgWithdrawFlowBatchSummary>('/v1/app/withdraw/v2/summary')")
    expect(apiSource).toContain("post<CreateWithdrawOrderResp>('/v1/app/withdraw/v2', data, {")
    expect(apiSource).not.toContain("'/api/v1/app/withdraw'")
  })

  it('adds the PP.MX security page from the reference security screen', () => {
    const source = readSource('src/pages/security/index.vue')
    const stylesSource = readSource('src/assets/styles/pp-mx-home.css')

    expect(source).toContain("name: 'security'")
    expect(source).toContain('requiresAuth: true')
    expect(source).toContain('PpmxSubpageLayout')
    expect(source).toContain('PpmxActionCard')
    expect(source).toContain('ppmx-security-page')
    expect(source).toContain('securityItems')
    expect(source).toContain('fa-key')
    expect(source).toContain('fa-envelope')
    expect(source).toContain('fa-mobile-screen')
    expect(source).toContain('openSecurityItem')
    expect(source).toContain("router.push('/sec-password')")
    expect(source).toContain("router.push('/sec-email')")
    expect(source).toContain("router.push('/sec-phone')")
    expect(source).toContain('showSoon')
    expect(stylesSource).toContain('.ppmx-security-page')
    expect(stylesSource).toContain('.ppmx-security-card')
  })

  it('adds the PP.MX security password page with the phone reset API contract', () => {
    const source = readSource('src/pages/sec-password/index.vue')
    const apiSource = readSource('src/api/user.ts')
    const stylesSource = readSource('src/assets/styles/pp-mx-home.css')

    expect(source).toContain("name: 'sec-password'")
    expect(source).toContain('requiresAuth: true')
    expect(source).toContain('page-id="page-sec-password"')
    expect(source).toContain('secPwPhone')
    expect(source).toContain('secPwCode')
    expect(source).toContain('secPwNew')
    expect(source).toContain('secPwConfirm')
    expect(source).toContain('sendTgSmsCode')
    expect(source).toContain('forgotPasswordByPhone')
    expect(source).toContain('useSubmitLock')
    expect(source).toContain("router.push('/security')")
    expect(source).toContain('buildMxPhoneWithDialCode')
    expect(apiSource).toContain('export interface ForgotPasswordByPhoneParams')
    expect(apiSource).toContain("post('/v1/app/tg/sendSMSCode'")
    expect(apiSource).toContain("post('/v1/app/tg/forgotPasswordByPhone'")
    expect(stylesSource).toContain('.ppmx-sec-password-page')
    expect(stylesSource).toContain('.ppmx-sec-password-form')
  })

  it('adds the PP.MX security email page with the RedPocketH5 bind email contract', () => {
    const source = readSource('src/pages/sec-email/index.vue')
    const apiSource = readSource('src/api/user.ts')
    const stylesSource = readSource('src/assets/styles/pp-mx-home.css')

    expect(source).toContain("name: 'sec-email'")
    expect(source).toContain('requiresAuth: true')
    expect(source).toContain('page-id="page-sec-email"')
    expect(source).toContain('secEmail')
    expect(source).toContain('bindCurrentTgEmail')
    expect(source).toContain('getCurrentUserInfo')
    expect(source).toContain('useSubmitLock')
    expect(source).toContain("router.push('/security')")
    expect(source).toContain('userStore.loadUserInfo')
    expect(apiSource).toContain('export interface TgBindEmailReq')
    expect(apiSource).toContain("post<{ email: string }>('/v1/app/tg/bindEmail'")
    expect(stylesSource).toContain('.ppmx-sec-email-page')
    expect(stylesSource).toContain('.ppmx-sec-email-form')
  })

  it('adds the PP.MX security phone page with the RedPocketH5 bind phone contract', () => {
    const source = readSource('src/pages/sec-phone/index.vue')
    const apiSource = readSource('src/api/user.ts')
    const stylesSource = readSource('src/assets/styles/pp-mx-home.css')

    expect(source).toContain("name: 'sec-phone'")
    expect(source).toContain('requiresAuth: true')
    expect(source).toContain('page-id="page-sec-phone"')
    expect(source).toContain('secPhOld')
    expect(source).toContain('secPhCode')
    expect(source).toContain('secPhNew')
    expect(source).toContain('sendTgSmsCode')
    expect(source).toContain('bindCurrentTgPhone')
    expect(source).toContain('getCurrentUserInfo')
    expect(source).toContain('useSubmitLock')
    expect(source).toContain("router.push('/security')")
    expect(source).toContain('buildMxPhoneWithDialCode')
    expect(source).toContain('userStore.loadUserInfo')
    expect(apiSource).toContain('export interface TgBindPhoneReq')
    expect(apiSource).toContain("post<{ phone: string; country: AppCountryCode }>('/v1/app/tg/bindPhone'")
    expect(stylesSource).toContain('.ppmx-sec-phone-page')
    expect(stylesSource).toContain('.ppmx-sec-phone-form')
  })

  it('adds an immersive API-backed PP.MX play page without gamePlay compatibility', () => {
    const source = readSource('src/pages/play/index.vue')
    const apiSource = readSource('src/api/game.ts')
    const homeSource = readSource('src/pages/ppmx-home/PpmxHome.vue')
    const stylesSource = readSource('src/assets/styles/pp-mx-home.css')

    expect(source).toContain("name: 'play'")
    expect(source).toContain('requiresAuth: true')
    expect(source).toContain("shell: 'none'")
    expect(source).toContain('launchAppGame')
    expect(source).toContain('gameId')
    expect(source).toContain('launchLanguage')
    expect(source).toContain('IFRAME_LOAD_TIMEOUT')
    expect(source).toContain('iframe')
    expect(source).toContain('ppmx-play-page')
    expect(source).toContain('openExternalGame')
    expect(source).toContain('reloadGame')
    expect(source).toContain('const userStore = useUserStore()')
    expect(source).toContain('refreshUserInfoAfterGameExit')
    expect(source).toContain('userStore.loadUserInfo()')
    expect(apiSource).toContain('export interface AppGameLaunchReq')
    expect(apiSource).toContain('export interface AppGameLaunchResp')
    expect(apiSource).toContain("post<AppGameLaunchResp>('/v1/app/appGame/launch'")
    expect(homeSource).toContain("path: '/play'")
    expect(homeSource).not.toContain('/gamePlay')
    expect(stylesSource).toContain('.ppmx-play-page')
    expect(stylesSource).toContain('.ppmx-play-frame')
  })

  it('adds an API-backed PP.MX casino category page from the reference casino screen', () => {
    const source = readSource('src/pages/casino/index.vue')
    const apiSource = readSource('src/api/game.ts')
    const chromeSource = readSource('src/pages/ppmx-home/components/PpmxPageChrome.vue')
    const homeSource = readSource('src/pages/ppmx-home/PpmxHome.vue')
    const stylesSource = readSource('src/assets/styles/pp-mx-home.css')

    expect(source).toContain("name: 'casino'")
    expect(source).toContain('requiresAuth: true')
    expect(source).toContain('PpmxPageChrome')
    expect(source).toContain('getAppGameCategoryList')
    expect(source).toContain('activeCategoryId')
    expect(source).toContain("type CasinoCategoryId = 'slots' | 'casino' | 'blockchain' | 'fishing' | 'rummy' | 'sports' | 'mini' | 'lottery'")
    expect(source).toContain("categoryCode: 'slots'")
    expect(source).toContain("categoryCode: 'casino'")
    expect(source).toContain("categoryCode: 'blockchain'")
    expect(source).toContain("categoryCode: 'fishing'")
    expect(source).toContain("categoryCode: 'rummy'")
    expect(source).toContain("categoryCode: 'sports'")
    expect(source).toContain("categoryCode: 'mini'")
    expect(source).toContain("categoryCode: 'lottery'")
    expect(source).toContain('payload.categoryCode = activeCategory.value.categoryCode')
    expect(source).toContain('searchKeyword')
    expect(source).toContain('sortMode')
    expect(source).toContain('casinoGrid')
    expect(source).toContain('loadMoreGames')
    expect(source).toContain("path: '/play'")
    expect(source).toContain('AppState')
    expect(source).not.toContain('/gamePlay')
    expect(apiSource).toContain('export interface AppGameListReq')
    expect(apiSource).toContain("post<AppGameCategoryListResp>('/v1/app/appGame/categoryList'")
    expect(apiSource).toContain("post<AppGameListResp>('/v1/app/appGame/list'")
    expect(apiSource).toContain("post<AppGameThirdCategoryResp>('/v1/app/appGame/thirdCategories'")
    expect(apiSource).not.toContain("'/api/v1/app/appGame")
    expect(chromeSource).toContain("target === 'casino'")
    expect(chromeSource).toContain("return '/casino'")
    expect(homeSource).toContain("router.push('/casino')")
    expect(homeSource).toContain('openCategoryList')
    expect(homeSource).toContain("categoryCode: category.id")
    expect(stylesSource).toContain('.ppmx-casino-page')
    expect(stylesSource).toContain('.ppmx-casino-grid')
    expect(stylesSource).toContain('.ppmx-casino-tab')
  })

  it('adds the API-backed PP.MX records page with separated record types', () => {
    const source = readSource('src/pages/records/index.vue')
    const apiSource = readSource('src/api/user.ts')
    const stylesSource = readSource('src/assets/styles/pp-mx-home.css')

    expect(source).toContain("name: 'records'")
    expect(source).toContain('requiresAuth: true')
    expect(source).toContain('PpmxPageChrome')
    expect(source).toContain('walletTime')
    expect(source).toContain('walletType')
    expect(source).toContain('walletCat')
    expect(source).toContain('walletSummary')
    expect(source).toContain('walletList')
    expect(source).toContain('PpmxSegmentedOptions')
    expect(source).toContain('PpmxMoneyText')
    expect(source).toContain("type RecordsType = 'deposit' | 'withdraw' | 'bet'")
    expect(source).toContain("type RecordsCategory = 'all' | 'slots' | 'casino' | 'blockchain' | 'fishing' | 'rummy' | 'sports' | 'mini' | 'lottery'")
    expect(source).toContain("{ value: 'all', label:")
    expect(source).toContain("{ value: 'slots', label:")
    expect(source).toContain("{ value: 'casino', label:")
    expect(source).toContain("{ value: 'blockchain', label:")
    expect(source).toContain("{ value: 'fishing', label:")
    expect(source).toContain("{ value: 'rummy', label:")
    expect(source).toContain("{ value: 'sports', label:")
    expect(source).toContain("{ value: 'mini', label:")
    expect(source).toContain("{ value: 'lottery', label:")
    expect(source).toContain("const selectedCategory = ref<RecordsCategory>('all')")
    expect(source).toContain("v-if=\"selectedType === 'bet'\"")
    expect(source).toContain('loadRecords')
    expect(source).toContain('filteredRecords')
    expect(source).toContain('getRechargeOrderHistory')
    expect(source).toContain('getWithdrawOrderHistory')
    expect(source).toContain('getAppUserBetRecordList')
    expect(source).not.toContain('getAppCashHistoryList')
    expect(apiSource).toContain("post<AppOrderHistoryResp>('/v1/app/rechargeOrder/list'")
    expect(apiSource).toContain("post<WithdrawOrderHistoryResp>('/v1/app/withdraw/list'")
    expect(apiSource).toContain("post<AppUserBetRecordResp>('/v1/app/appUserBetRecord/list'")
    expect(stylesSource).toContain('.ppmx-records-page')
    expect(stylesSource).toContain('.ppmx-records-filter')
    expect(stylesSource).toContain('.ppmx-records-card')
  })

  it('adds the PP.MX user profile page from the reference profile screen', () => {
    const source = readSource('src/pages/user-profile/index.vue')
    const stylesSource = readSource('src/assets/styles/pp-mx-home.css')
    const apiSource = readSource('src/api/user.ts')

    expect(source).toContain("name: 'user-profile'")
    expect(source).toContain('requiresAuth: true')
    expect(source).toContain('PpmxPageChrome')
    expect(source).toContain('profileAvatar')
    expect(source).toContain('profileUserInput')
    expect(source).toContain('profileHandle')
    expect(source).toContain('profileDetailsForm')
    expect(source).toContain('PpmxField')
    expect(source).toContain('usePpmxPageRequest')
    expect(source).toContain('saveProfile')
    expect(source).toContain('updateCurrentTgName')
    expect(source).toContain('updateCurrentTgAvatar')
    expect(source).toContain('appUpload')
    expect(source).not.toContain('lastName')
    expect(apiSource).toContain("upload<{ url: string }>('/v1/app/upload'")
    expect(apiSource).toContain("post<{ avatar: string }>('/v1/app/tg/avatar'")
    expect(apiSource).toContain("post<{ username: string }>('/v1/app/tg/name'")
    expect(stylesSource).toContain('.ppmx-user-profile-page')
    expect(stylesSource).toContain('.ppmx-user-profile-card')
  })

  it('adds the PP.MX withdrawal account page from the reference bank screen', () => {
    const source = readSource('src/pages/bank/index.vue')
    const stylesSource = readSource('src/assets/styles/pp-mx-home.css')

    expect(source).toContain("name: 'bank'")
    expect(source).toContain('requiresAuth: true')
    expect(source).toContain('PpmxPageChrome')
    expect(source).toContain('bankList')
    expect(source).toContain('APP_COUNTRY_CODE')
    expect(source).toContain('withdrawFields')
    expect(source).toContain('fieldValues')
    expect(source).toContain('getCountryWithdrawFields')
    expect(source).toContain('submitBankAccount')
    expect(source).toContain('accountData')
    expect(source).toContain('handleDelete')
    expect(stylesSource).toContain('.ppmx-bank-page')
    expect(stylesSource).toContain('.ppmx-bank-card')
  })

  it('adds the PP.MX VIP page from the reference VIP screen', () => {
    const source = readSource('src/pages/vip/index.vue')
    const stylesSource = readSource('src/assets/styles/pp-mx-home.css')
    const chromeSource = readSource('src/pages/ppmx-home/components/PpmxPageChrome.vue')
    const homeSource = readSource('src/pages/ppmx-home/PpmxHome.vue')
    const profileSource = readSource('src/pages/profile/index.vue')
    const typesSource = readSource('src/pages/ppmx-home/types.ts')

    expect(source).toContain("name: 'vip'")
    expect(source).toContain('requiresAuth: true')
    expect(source).toContain('PpmxPageChrome')
    expect(source).toContain('vipCurrentName')
    expect(source).toContain('vipPtsNow')
    expect(source).toContain('vipNextName')
    expect(source).toContain('vipPtsNext')
    expect(source).toContain('vipBar')
    expect(source).toContain('vipRemain')
    expect(source).toContain('vipLevels')
    expect(source).toContain('vipRewards')
    expect(stylesSource).toContain('.ppmx-vip-page')
    expect(stylesSource).toContain('.ppmx-vip-level-card')
    expect(chromeSource).toContain("target === 'vip'")
    expect(chromeSource).toContain("return '/vip'")
    expect(homeSource).toContain("target === 'vip'")
    expect(profileSource).toContain("router.push('/vip')")
    expect(typesSource).toContain("| 'vip'")
  })

  it('adds the PP.MX recharge page with real API integration and no static fallback', () => {
    const source = readSource('src/pages/recharge/index.vue')
    const apiSource = readSource('src/api/user.ts')

    expect(source).toContain("name: 'recharge'")
    expect(source).toContain('requiresAuth: true')
    expect(source).toContain('PpmxPageChrome')
    expect(source).toContain('AppState')
    expect(source).toContain('getAppCountries')
    expect(source).toContain('getCountryRechargeInfo')
    expect(source).toContain('getCountryRechargeFields')
    expect(source).toContain('getRechargeIsFirstV2')
    expect(source).toContain('createRechargeOrderV2')
    expect(source).toContain('calculateRechargeBonusRate')
    expect(source).toContain('calculateRechargeBonusAmount')
    expect(source).toContain('useSubmitLock')
    expect(source).toContain('countryCode: APP_COUNTRY_CODE')
    expect(source).toContain('currency: selectedCountry.value?.currencyCode || APP_CURRENCY')
    expect(source).toContain('refreshRechargeFirstStatus')
    expect(source).toContain('merchantOrderNo: buildMerchantOrderNo()')
    expect(source).not.toContain('exchangeRate')
    expect(source).not.toContain('country.rate')
    expect(source).not.toContain('getRechargePromotions')
    expect(apiSource).toContain("get<AppCountryItem[]>('/v1/app/countries')")
    expect(apiSource).toContain("get<RechargeFirstStatusResp>('/v1/app/recharge/isFirst/v2'")
    expect(apiSource).toContain("post<RechargeOrderAppBack>('/v1/app/rechargeOrder/v2'")
    expect(apiSource).not.toContain("'/api/v1/app/rechargeOrder'")
  })

  it('renders recharge payment as PP.MX deposit modal UI instead of redirecting directly', () => {
    const source = readSource('src/pages/recharge/index.vue')
    const paymentModalSource = readSource('src/components/PpmxRechargePaymentModal.vue')
    const stylesSource = readSource('src/assets/styles/pp-mx-home.css')

    expect(source).toContain('PpmxRechargePaymentModal')
    expect(source).toContain('Legacy PpmxBaseModal payment popup retired')
    expect(source).toContain('const paymentOrder = ref<RechargeOrderAppBack | null>(null)')
    expect(source).toContain('showPaymentModal.value = true')
    expect(source).toContain('id="depositModal"')
    expect(source).toContain('class="ppmx-recharge-modal"')
    expect(source).toContain('async function goToCryptoPay()')
    expect(source).toContain("path: '/crypto-pay'")
    expect(source).toContain("channelName: 'Cash'")
    expect(source).toContain("channelName: 'Apple Pay'")
    expect(source).toContain("channelName: 'Google Pay'")
    expect(source).toContain('channelCode: CRYPTO_CHANNEL_CODE')
    expect(source).not.toContain('v-for="method in payMethods"')
    expect(paymentModalSource).toContain('id="paymentModal"')
    expect(paymentModalSource).toContain('class="ppmx-recharge-modal ppmx-recharge-payment-modal"')
    expect(paymentModalSource).toContain('ppmx-recharge-modal__card')
    expect(paymentModalSource).toContain('ppmx-recharge-modal__scroll')
    expect(paymentModalSource).toContain('dep-scroll')
    expect(paymentModalSource).toContain('function openPaymentUrl()')
    expect(paymentModalSource).toContain("window.open(paymentUrl.value, '_blank', 'noopener,noreferrer')")
    expect(source).not.toContain('window.location.href = order.payUrl')
    expect(stylesSource).toContain('.ppmx-recharge-modal')
    expect(stylesSource).toContain('.ppmx-recharge-modal__card')
    expect(stylesSource).toContain('.ppmx-recharge-payment-modal')
    expect(stylesSource).toContain('font-size: 0.875rem')
    expect(stylesSource).toContain('font-size: 0.75rem')
  })

  it('uses the shared select input for dynamic recharge select fields', () => {
    const source = readSource('src/pages/recharge/index.vue')

    expect(source).toContain('PpmxSelectInput')
    expect(source).toContain(':options="fieldOptions(field)"')
    expect(source).toContain('v-model="fieldValues[field.fieldKey]"')
    expect(source).not.toContain('selectingField')
    expect(source).not.toContain('showFieldPicker')
    expect(source).not.toContain('ppmx-recharge-select')
    expect(source).not.toContain('ppmx-recharge-popup')
  })

  it('hides recharge gift amounts when depositing into the sports wallet', () => {
    const rechargePageSource = readSource('src/pages/recharge/index.vue')
    const rechargeModalSource = readSource('src/components/PpmxRechargeModal.vue')

    for (const source of [rechargePageSource, rechargeModalSource]) {
      expect(source).toContain("selectedWalletType.value === 'sport'")
      expect(source).toContain('effectiveBonusRate')
      expect(source).toContain('effectiveBonusAmount')
      expect(source).toContain("const showPromo = computed(() => Boolean(rechargeFirstStatus.value) && !isSportsWalletRecharge.value)")
      expect(source).toContain('effectiveBonusAmount.value')
      expect(source).not.toContain('bonusRate: bonusRate.value')
      expect(source).not.toContain('bonusAmount: bonusAmount.value')
    }
  })

  it('offers balance and sports recharge wallets and switches the available balance', () => {
    const rechargePageSource = readSource('src/pages/recharge/index.vue')
    const rechargeModalSource = readSource('src/components/PpmxRechargeModal.vue')

    for (const source of [rechargePageSource, rechargeModalSource]) {
      expect(source).toContain('selectedRechargeWalletBalance')
      expect(source).toContain('userStore.userInfo?.sportBalance')
      expect(source).toContain('userStore.userInfo?.balance')
      expect(source).toContain('formatMoney(toDisplayCents(selectedRechargeWalletBalance.value)')
      expect(source).toContain("value: 'balance'")
      expect(source).toContain("value: 'sport'")
      expect(source).toContain("t('recharge.walletBalance')")
      expect(source).toContain("t('recharge.walletSport')")
      expect(source).not.toContain('formatMoney(toDisplayCents(userStore.userInfo?.balance)')
    }
  })

  it('sets the minimum recharge amount to 50', () => {
    const rechargePageSource = readSource('src/pages/recharge/index.vue')
    const rechargeModalSource = readSource('src/components/PpmxRechargeModal.vue')

    for (const source of [rechargePageSource, rechargeModalSource]) {
      expect(source).toContain('const rechargeAmounts = [50, 100, 200, 500, 1000, 5000, 10000] as const')
      expect(source).toContain('const MIN_RECHARGE_AMOUNT = rechargeAmounts[0]')
      expect(source).toContain('const selectedAmount = ref<number>(rechargeAmounts[0])')
      expect(source).not.toContain('const rechargeAmounts = [20, 30, 50')
    }
  })

  it('adds the PP.MX responsible gaming page from the reference page-responsible', () => {
    const source = readSource('src/pages/responsible/index.vue')
    const stylesSource = readSource('src/assets/styles/pp-mx-home.css')
    const chromeSource = readSource('src/pages/ppmx-home/components/PpmxPageChrome.vue')
    const homeSource = readSource('src/pages/ppmx-home/PpmxHome.vue')
    const authGateSource = readSource('src/utils/authGate.ts')

    expect(source).toContain("name: 'responsible'")
    expect(source).toContain("shell: 'ppmx'")
    expect(source).toContain('requiresAuth: false')
    expect(source).toContain('id="page-responsible"')
    expect(source).toContain('PpmxPageChrome')
    expect(source).toContain('depositLimit')
    expect(source).toContain('sessionTime')
    expect(source).toContain('exclusionOptions')
    expect(source).toContain('applyResponsibleSetting')
    expect(source).toContain('PP.MX SUPPORT')
    expect(stylesSource).toContain('.ppmx-responsible-page')
    expect(stylesSource).toContain('.ppmx-responsible-card--exclude')
    expect(stylesSource).toContain('.ppmx-responsible-hotline')
    expect(chromeSource).toContain("target === 'responsible'")
    expect(chromeSource).toContain("return '/responsible'")
    expect(homeSource).toContain("target === 'responsible'")
    expect(homeSource).toContain("router.push('/responsible')")
    expect(authGateSource).toContain("PUBLIC_INFO_ROUTES = ['/responsible']")
  })
})
