/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppConfirmDialog: typeof import('./../components/AppConfirmDialog.vue')['default']
    AppEmpty: typeof import('./../components/AppEmpty.vue')['default']
    AppPageHeader: typeof import('./../components/AppPageHeader.vue')['default']
    AppTopHeader: typeof import('./../components/AppTopHeader.vue')['default']
    Chart: typeof import('./../components/Chart/index.vue')['default']
    CoinAmount: typeof import('./../components/CoinAmount.vue')['default']
    CurrencyText: typeof import('./../components/CurrencyText.vue')['default']
    GhostButton: typeof import('./../components/GhostButton.vue')['default']
    LuckyActionGrid: typeof import('./../components/LuckyActionGrid.vue')['default']
    LuckyGrabModal: typeof import('./../components/LuckyGrabModal.vue')['default']
    NavBar: typeof import('./../components/NavBar.vue')['default']
    ParityChoiceDialog: typeof import('./../components/ParityChoiceDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SendPacketForm: typeof import('./../components/SendPacketForm.vue')['default']
    TabBar: typeof import('./../components/TabBar.vue')['default']
    TelegramLogin: typeof import('./../components/TelegramLogin.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCollapse: typeof import('vant/es')['Collapse']
    VanCollapseItem: typeof import('vant/es')['CollapseItem']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanDatePicker: typeof import('vant/es')['DatePicker']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanIcon: typeof import('vant/es')['Icon']
    VanList: typeof import('vant/es')['List']
    VanLoading: typeof import('vant/es')['Loading']
    VanNoticeBar: typeof import('vant/es')['NoticeBar']
    VanOverlay: typeof import('vant/es')['Overlay']
    VanPopup: typeof import('vant/es')['Popup']
    VanSkeleton: typeof import('vant/es')['Skeleton']
    VanSkeletonAvatar: typeof import('vant/es')['SkeletonAvatar']
    VanSkeletonImage: typeof import('vant/es')['SkeletonImage']
    VanStepper: typeof import('vant/es')['Stepper']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanSwitch: typeof import('vant/es')['Switch']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VipProgressPopup: typeof import('./../components/VipProgressPopup.vue')['default']
  }
}
