/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'Home': RouteRecordInfo<
      'Home',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '404': RouteRecordInfo<
      '404',
      '/:all(.*)',
      { all: ParamValue<true> },
      { all: ParamValue<false> },
      | never
    >,
    '/bindEmail/': RouteRecordInfo<
      '/bindEmail/',
      '/bindEmail',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/bindPhone/': RouteRecordInfo<
      '/bindPhone/',
      '/bindPhone',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/bindTg/': RouteRecordInfo<
      '/bindTg/',
      '/bindTg',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'CheckIn': RouteRecordInfo<
      'CheckIn',
      '/checkin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/cs/': RouteRecordInfo<
      '/cs/',
      '/cs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Demo': RouteRecordInfo<
      'Demo',
      '/demo',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'FirstDeposit': RouteRecordInfo<
      'FirstDeposit',
      '/firstDeposit',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'History': RouteRecordInfo<
      'History',
      '/history',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Invite': RouteRecordInfo<
      'Invite',
      '/invite',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'KeepAlive': RouteRecordInfo<
      'KeepAlive',
      '/keepalive',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Login': RouteRecordInfo<
      'Login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'LuckyDetail': RouteRecordInfo<
      'LuckyDetail',
      '/luckyDetail',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'LuckyWheel': RouteRecordInfo<
      'LuckyWheel',
      '/luckyWheel',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'PacketList': RouteRecordInfo<
      'PacketList',
      '/packetList',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Prize': RouteRecordInfo<
      'Prize',
      '/prize',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Profile': RouteRecordInfo<
      'Profile',
      '/profile',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Questions': RouteRecordInfo<
      'Questions',
      '/questions',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Rebate': RouteRecordInfo<
      'Rebate',
      '/rebate',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'RebateWithdraw': RouteRecordInfo<
      'RebateWithdraw',
      '/rebateWithdraw',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Recharge': RouteRecordInfo<
      'Recharge',
      '/recharge',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'RechargeRecord': RouteRecordInfo<
      'RechargeRecord',
      '/rechargeRecord',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'ReferralCommission': RouteRecordInfo<
      'ReferralCommission',
      '/referralCommission',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Register': RouteRecordInfo<
      'Register',
      '/register',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'ForgotPassword': RouteRecordInfo<
      'ForgotPassword',
      '/resetpwd',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'SendPacket': RouteRecordInfo<
      'SendPacket',
      '/sendPacket',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Setting': RouteRecordInfo<
      'Setting',
      '/setting',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Team': RouteRecordInfo<
      'Team',
      '/team',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'ThreeSpinBonus': RouteRecordInfo<
      'ThreeSpinBonus',
      '/threeSpinBonus',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Transform': RouteRecordInfo<
      'Transform',
      '/transform',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'TrialFlowLottery': RouteRecordInfo<
      'TrialFlowLottery',
      '/trialFlowLottery',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'VipActivity': RouteRecordInfo<
      'VipActivity',
      '/vipActivity',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Wallet': RouteRecordInfo<
      'Wallet',
      '/wallet',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Withdraw': RouteRecordInfo<
      'Withdraw',
      '/withdraw',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'WithdrawAccount': RouteRecordInfo<
      'WithdrawAccount',
      '/withdrawAccount',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'WithdrawRecord': RouteRecordInfo<
      'WithdrawRecord',
      '/withdrawRecord',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | 'Home'
      views:
        | never
    }
    'src/pages/[...all].vue': {
      routes:
        | '404'
      views:
        | never
    }
    'src/pages/bindEmail/index.vue': {
      routes:
        | '/bindEmail/'
      views:
        | never
    }
    'src/pages/bindPhone/index.vue': {
      routes:
        | '/bindPhone/'
      views:
        | never
    }
    'src/pages/bindTg/index.vue': {
      routes:
        | '/bindTg/'
      views:
        | never
    }
    'src/pages/checkin/index.vue': {
      routes:
        | 'CheckIn'
      views:
        | never
    }
    'src/pages/cs/index.vue': {
      routes:
        | '/cs/'
      views:
        | never
    }
    'src/pages/demo/index.vue': {
      routes:
        | 'Demo'
      views:
        | never
    }
    'src/pages/firstDeposit/index.vue': {
      routes:
        | 'FirstDeposit'
      views:
        | never
    }
    'src/pages/history/index.vue': {
      routes:
        | 'History'
      views:
        | never
    }
    'src/pages/invite/index.vue': {
      routes:
        | 'Invite'
      views:
        | never
    }
    'src/pages/keepalive/index.vue': {
      routes:
        | 'KeepAlive'
      views:
        | never
    }
    'src/pages/login/index.vue': {
      routes:
        | 'Login'
      views:
        | never
    }
    'src/pages/luckyDetail/index.vue': {
      routes:
        | 'LuckyDetail'
      views:
        | never
    }
    'src/pages/luckyWheel/index.vue': {
      routes:
        | 'LuckyWheel'
      views:
        | never
    }
    'src/pages/packetList/index.vue': {
      routes:
        | 'PacketList'
      views:
        | never
    }
    'src/pages/prize/index.vue': {
      routes:
        | 'Prize'
      views:
        | never
    }
    'src/pages/profile/index.vue': {
      routes:
        | 'Profile'
      views:
        | never
    }
    'src/pages/questions/index.vue': {
      routes:
        | 'Questions'
      views:
        | never
    }
    'src/pages/rebate/index.vue': {
      routes:
        | 'Rebate'
      views:
        | never
    }
    'src/pages/rebateWithdraw/index.vue': {
      routes:
        | 'RebateWithdraw'
      views:
        | never
    }
    'src/pages/recharge/index.vue': {
      routes:
        | 'Recharge'
      views:
        | never
    }
    'src/pages/rechargeRecord/index.vue': {
      routes:
        | 'RechargeRecord'
      views:
        | never
    }
    'src/pages/referralCommission/index.vue': {
      routes:
        | 'ReferralCommission'
      views:
        | never
    }
    'src/pages/register/index.vue': {
      routes:
        | 'Register'
      views:
        | never
    }
    'src/pages/resetpwd/index.vue': {
      routes:
        | 'ForgotPassword'
      views:
        | never
    }
    'src/pages/sendPacket/index.vue': {
      routes:
        | 'SendPacket'
      views:
        | never
    }
    'src/pages/setting/index.vue': {
      routes:
        | 'Setting'
      views:
        | never
    }
    'src/pages/team/index.vue': {
      routes:
        | 'Team'
      views:
        | never
    }
    'src/pages/threeSpinBonus/index.vue': {
      routes:
        | 'ThreeSpinBonus'
      views:
        | never
    }
    'src/pages/transform/index.vue': {
      routes:
        | 'Transform'
      views:
        | never
    }
    'src/pages/trialFlowLottery/index.vue': {
      routes:
        | 'TrialFlowLottery'
      views:
        | never
    }
    'src/pages/vipActivity/index.vue': {
      routes:
        | 'VipActivity'
      views:
        | never
    }
    'src/pages/wallet/index.vue': {
      routes:
        | 'Wallet'
      views:
        | never
    }
    'src/pages/withdraw/index.vue': {
      routes:
        | 'Withdraw'
      views:
        | never
    }
    'src/pages/withdrawAccount/index.vue': {
      routes:
        | 'WithdrawAccount'
      views:
        | never
    }
    'src/pages/withdrawRecord/index.vue': {
      routes:
        | 'WithdrawRecord'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
