import { describe, expect, it } from 'vitest'

const { readFileSync } = await import('node:' + 'fs')
const profileSource = readFileSync(new URL('./index.vue', import.meta.url), 'utf8')
const userApiSource = readFileSync(new URL('../../api/user.ts', import.meta.url), 'utf8')
const ppmxStylesSource = readFileSync(new URL('../../assets/styles/pp-mx-home.css', import.meta.url), 'utf8')
const rechargeModalSource = readFileSync(new URL('../../components/PpmxRechargeModal.vue', import.meta.url), 'utf8')
const rechargePaymentModalSource = readFileSync(new URL('../../components/PpmxRechargePaymentModal.vue', import.meta.url), 'utf8')
const zhLocaleSource = readFileSync(new URL('../../locales/zh-CN.ts', import.meta.url), 'utf8')
const enLocaleSource = readFileSync(new URL('../../locales/en-US.ts', import.meta.url), 'utf8')
const esLocaleSource = readFileSync(new URL('../../locales/es-PE.ts', import.meta.url), 'utf8')

describe('profile dynamic user data', () => {
  it('loads profile data for logged-in sessions and renders explicit loading/error/empty states', () => {
    expect(profileSource).toContain('loadProfileData')
    expect(profileSource).toContain('userStore.loadUserInfo()')
    expect(profileSource).toContain('profileLoading')
    expect(profileSource).toContain('profileLoadError')
    expect(profileSource).toContain('profileReady')
    expect(profileSource).toContain('<AppState')
    expect(profileSource).toContain('@retry="loadProfileData"')
  })

  it('does not fall back to hardcoded PP.PE account data when a logged-in profile is missing', () => {
    expect(profileSource).not.toContain("|| 'pp.pe'")
    expect(profileSource).not.toContain(": 'ID PP.PE'")
    expect(profileSource).not.toContain('class="ppmx-account-avatar">pp.pe</span>')
  })

  it('keeps deposit, withdraw, and withdrawal account actions on one mobile row', () => {
    const mobileSection = ppmxStylesSource.slice(ppmxStylesSource.indexOf('@media (max-width: 640px)'))

    expect(mobileSection).toContain('.ppmx-account-actions')
    expect(mobileSection).toContain('grid-template-columns: repeat(3, minmax(0, 1fr))')
    expect(mobileSection).not.toMatch(/\.ppmx-account-actions\s*\{\s*grid-template-columns:\s*1fr;/)
  })

  it('allows copying the raw account id from the balance card', () => {
    expect(profileSource).toContain('accountIdValue')
    expect(profileSource).toContain('copyAccountId')
    expect(profileSource).toContain('navigator.clipboard.writeText(accountIdValue.value)')
    expect(profileSource).toContain('copyIdSuccess')
    expect(profileSource).toContain('copyIdFailure')
    expect(profileSource).toContain('id="accIdCopy"')
    expect(profileSource).toContain('@click="copyAccountId"')
    expect(ppmxStylesSource).toContain('.ppmx-account-id-copy')
  })

  it('shows total, balance wallet, and sports wallet amounts in the profile balance card', () => {
    expect(profileSource).toContain('accountTotalBalanceCents')
    expect(profileSource).toContain('accountWalletItems')
    expect(profileSource).toContain('userStore.userInfo?.sportBalance')
    expect(profileSource).toContain('id="balMain"')
    expect(profileSource).toContain('ppmx-account-wallets')
    expect(profileSource).toContain('ppmx-account-wallet-row')
    expect(profileSource).toContain('walletBalance')
    expect(profileSource).toContain('walletSport')
    expect(ppmxStylesSource).toContain('.ppmx-account-balance #balMain')
    expect(ppmxStylesSource).toContain('font-size: clamp(2.05rem, 6.8vw, 3.35rem)')
    expect(ppmxStylesSource).toContain('.ppmx-account-wallets')
    expect(ppmxStylesSource).toContain('.ppmx-account-wallet-row')
  })

  it('only allows sports wallet balance transfer into the balance wallet from the profile card', () => {
    expect(userApiSource).toContain("'/v1/app/tg/wallet/transfer'")
    expect(profileSource).toContain('transferTgWalletBalance')
    expect(profileSource).toContain('walletTransferModalOpen')
    expect(profileSource).toContain('openWalletTransfer(wallet.id)')
    expect(profileSource).toContain("wallet.id === 'sport'")
    expect(profileSource).toContain('id="walletTransferModal"')
    expect(profileSource).toContain('walletTransferSourceBalanceCents')
    expect(profileSource).toContain('transferAllSportBalance')
    expect(profileSource).toContain('confirmWalletTransfer')
    expect(profileSource).toContain('walletTransferTargetOptions')
    expect(profileSource).toContain("fromWallet: 'sport'")
    expect(profileSource).toContain("toWallet: 'balance'")
    expect(profileSource).toContain('userStore.userInfo.balance = resp.balance')
    expect(profileSource).toContain('userStore.userInfo.sportBalance = resp.sportBalance')
    expect(profileSource).toContain('profileText.walletTransferTitle')
    expect(ppmxStylesSource).toContain('.ppmx-account-wallet-transfer')
    expect(ppmxStylesSource).toContain('.ppmx-account-wallet-transfer-btn')
    expect(ppmxStylesSource).toContain('.ppmx-account-wallet-row__amount span')
    expect(ppmxStylesSource).toContain('font-size: 12px')
    expect(ppmxStylesSource).toContain('var(--ppmx-gold')
  })

  it('hides the bank prompt when the current user already has a withdrawal account', () => {
    expect(profileSource).toContain('showBankPrompt')
    expect(profileSource).toContain('userStore.userInfo?.hasWithdrawAccount !== true')
    expect(profileSource).toContain('v-if="showBankPrompt"')
    expect(profileSource).toContain('id="bankPrompt"')
  })

  it('redeems promo codes through the exchange code API and refreshes balance', () => {
    expect(profileSource).toContain('redeemExchangeCode')
    expect(userApiSource).toContain("'/v1/app/exchangeCode/redeem'")
    expect(profileSource).toContain('submitPromoCodeRequest')
    expect(profileSource).toContain('isPromoSubmitting')
    expect(profileSource).toContain('await userStore.loadUserInfo()')
    expect(profileSource).not.toContain('promoCodeSoon')
  })

  it('opens recharge inside the profile page modal instead of routing away', () => {
    expect(profileSource).toContain('PpmxRechargeModal')
    expect(profileSource).toContain('rechargeModalOpen')
    expect(profileSource).toContain('function openRecharge()')
    expect(profileSource).toContain('rechargeModalOpen.value = true')
    expect(profileSource).toContain('function closeRechargeModal()')
    expect(profileSource).toContain('v-model="rechargeModalOpen"')
    expect(profileSource).toContain('route.query.recharge')
    expect(profileSource).toContain("recharge !== 'open'")
    expect(profileSource).toContain('delete query.recharge')
    expect(profileSource).not.toContain("router.push('/recharge')")
  })

  it('shows the profile recharge payment popup after a v2 order is created', () => {
    expect(userApiSource).toContain("'/v1/app/rechargeOrder/v2'")
    expect(rechargeModalSource).toContain('PpmxRechargePaymentModal')
    expect(rechargeModalSource).toContain('const paymentOrder = ref<RechargeOrderAppBack | null>(null)')
    expect(rechargeModalSource).toContain('showPaymentModal.value = true')
    expect(rechargeModalSource).toContain('paymentOrder.value = order')
    expect(rechargeModalSource).toContain('Legacy PpmxBaseModal payment popup retired')
    expect(rechargeModalSource).toContain('id="depositModal"')
    expect(rechargeModalSource).toContain('async function goToCryptoPay()')
    expect(rechargeModalSource).toContain("path: '/crypto-pay'")
    expect(rechargeModalSource).toContain('getCountryRechargeInfo(APP_COUNTRY_CODE)')
    expect(rechargeModalSource).toContain('channels: info?.channels ?? []')
    expect(rechargeModalSource).not.toContain("channelName: 'Cash'")
    expect(rechargeModalSource).not.toContain("channelName: 'Apple Pay'")
    expect(rechargeModalSource).not.toContain("channelName: 'Google Pay'")
    expect(rechargeModalSource).not.toContain('v-for="method in payMethods"')
    expect(rechargePaymentModalSource).toContain('id="paymentModal"')
    expect(rechargePaymentModalSource).toContain('class="ppmx-recharge-modal ppmx-recharge-payment-modal"')
    expect(rechargePaymentModalSource).toContain('ppmx-recharge-modal__card')
    expect(rechargePaymentModalSource).toContain('dep-scroll')
    expect(rechargePaymentModalSource).toContain('function openPaymentUrl()')
    expect(rechargePaymentModalSource).toContain("window.open(paymentUrl.value, '_blank', 'noopener,noreferrer')")
    expect(rechargePaymentModalSource).toContain('function copyPaymentUrl()')
    expect(rechargeModalSource).not.toContain('window.location.href = url')
    expect(rechargeModalSource).not.toContain('redirectToPaymentUrl(order.payUrl)')
  })

  it('requires a payment amount warning confirmation before creating a profile recharge order', () => {
    const confirmIndex = rechargeModalSource.indexOf('await confirmPaymentAmountMatch()')
    const orderIndex = rechargeModalSource.indexOf('const order = await createOrderWithConfirm(payload)')

    expect(rechargeModalSource).toContain('async function confirmPaymentAmountMatch()')
    expect(rechargeModalSource).toContain("title: t('recharge.paymentAmountConfirmTitle')")
    expect(rechargeModalSource).toContain("message: t('recharge.paymentAmountConfirmMessage')")
    expect(rechargeModalSource).toContain("confirmButtonText: t('recharge.paymentAmountConfirmAction')")
    expect(rechargeModalSource).toContain('if (!await confirmPaymentAmountMatch()) return')
    expect(confirmIndex).toBeGreaterThan(-1)
    expect(orderIndex).toBeGreaterThan(-1)
    expect(confirmIndex).toBeLessThan(orderIndex)
    expect(zhLocaleSource).toContain('拉起金额与支付金额不同，资金将不会到账')
    expect(enLocaleSource).toContain('If the opened payment amount is different from the payment amount')
    expect(esLocaleSource).toContain('Si el monto abierto para pagar es distinto del monto a pagar')
  })

  it('matches the PP.PE Apple withdraw modal reference structure', () => {
    expect(profileSource).toContain('id="withdrawModal"')
    expect(profileSource).toContain("withdrawWagerComplete ? 'wd-badge--ok' : 'wd-badge--bad'")
    expect(profileSource).toContain('<div class="wd-rules">')
    expect(profileSource).toContain('class="wd-rules-t"')
    expect(profileSource).toContain('class="wd-rules-list"')
    expect(profileSource).not.toContain('<details class="wd-rules"')
    expect(ppmxStylesSource).toContain('rgba(255, 215, 0, 0.36)')
    expect(ppmxStylesSource).toContain('.wd-badge--bad')
    expect(ppmxStylesSource).toContain('.wd-rules-list li::before')
  })

  it('shows backend v2 withdrawal failure reasons instead of a generic fallback', () => {
    expect(profileSource).toContain('function getWithdrawSubmitErrorMessage(error: unknown)')
    expect(profileSource).toContain('error instanceof Error ? error.message.trim()')
    expect(profileSource).toContain('showToast(getWithdrawSubmitErrorMessage(error))')
    expect(profileSource).toContain('void loadWithdrawSummary()')
    expect(userApiSource).toContain("post<CreateWithdrawOrderResp>('/v1/app/withdraw/v2', data, {")
    expect(userApiSource).toContain('meta: { showError: false }')
  })

  it('uses 50 PEN as the minimum for regular withdrawals', () => {
    expect(profileSource).toContain('const withdrawMinCents = 5_000')
    expect(profileSource).toContain('min="50"')
    expect(profileSource).toContain('Monto mínimo de retiro: S/50.00 PEN')
    expect(profileSource).toContain('Minimum withdrawal: S/50.00 PEN')
    expect(profileSource).toContain('最低提现金额为 S/50.00 PEN')
    expect(profileSource).toContain('Monto mínimo de retiro: 50.')
    expect(profileSource).toContain('Minimum withdrawal amount: 50.')
    expect(profileSource).toContain('最低提现金额：50。')

    expect(esLocaleSource).toContain("commissionWithdrawMinToast: 'Monto mínimo de retiro de comisión: S/50.00 PEN'")
    expect(enLocaleSource).toContain("commissionWithdrawMinToast: 'Minimum commission withdrawal: S/50.00 PEN'")
    expect(zhLocaleSource).toContain("commissionWithdrawMinToast: '最低佣金提现金额为 S/50.00 PEN'")
  })
})
